#!/usr/bin/env bash
# sync-docs.sh — sync master (carbon_modern/docs/) to mirror (docs/),
# commit+push to docs.billing.smit34.ru, deploy to production server.
#
# Usage: from carbon_modern/docs/ dir, run:  ./sync-docs.sh "commit message"
#
# What it does:
#   1. Rebuild search index (search-index.json)
#   2. Mirror carbon_modern/docs/* -> ../../docs/  (excluding .git)
#   3. Commit + push in docs/ (separate docs.billing.smit34.ru repo)
#   4. Deploy same files to root@31.44.7.144:/var/www/docs.billing.smit34.ru/
#
# Master stays in carbon_modern/docs/ — always edit here.

set -euo pipefail

MSG="${1:-docs: sync from master}"
HERE="$(cd "$(dirname "$0")" && pwd)"
MIRROR="$(cd "$HERE/../../docs" && pwd)"
SERVER_PATH="/var/www/docs.billing.smit34.ru"

if command -v py >/dev/null 2>&1; then PY=py; else PY=python3; fi

echo "=== 0a. Auto-update version.js from billing/version.py + git log date ==="
(cd "$HERE/.." && PYTHONIOENCODING=utf-8 $PY - <<'PYEOF'
"""Авто-обновление docs/js/version.js — единого источника истины для подвала docs-сайта.

Источники:
  - VERSION / BUILD: billing/version.py (бампается при каждом деплое)
  - updated: дата последнего коммита, затронувшего carbon_modern/docs/ (в формате DD.MM.YYYY)
  - year: текущий год

Файл version.js перезаписывается полностью при каждом запуске sync-docs.sh.
После этого шаг 0 синхронизирует значения в HTML fallback-ы.
"""
import re, subprocess, sys
from datetime import datetime
sys.stdout.reconfigure(encoding='utf-8')

# 1. Read VERSION/BUILD from billing/version.py
src = open('billing/version.py', 'r', encoding='utf-8').read()
ver_m = re.search(r"VERSION\s*=\s*'([^']+)'", src)
bld_m = re.search(r"BUILD\s*=\s*'([^']+)'", src)
if not (ver_m and bld_m):
    print('  WARN: cannot parse billing/version.py — skip')
    raise SystemExit(0)
version, build = ver_m.group(1), bld_m.group(1)

# 2. Last commit date for docs/ (DD.MM.YYYY). Fallback: today.
try:
    out = subprocess.check_output(
        ['git', 'log', '-1', '--format=%cI', '--', 'docs/'],
        text=True, encoding='utf-8'
    ).strip()
    if out:
        # %cI = ISO-8601 strict, e.g. 2026-04-30T18:25:30+03:00
        dt = datetime.fromisoformat(out)
        updated = dt.strftime('%d.%m.%Y')
    else:
        updated = datetime.now().strftime('%d.%m.%Y')
except Exception as e:
    print('  WARN: git log failed (%s) — using today' % e)
    updated = datetime.now().strftime('%d.%m.%Y')

year = str(datetime.now().year)

# 3. Rewrite docs/js/version.js
new_js = """/**
 * Single source of truth for the docs version/build/update date.
 * Auto-generated by sync-docs.sh from billing/version.py + last git commit date.
 * Manual edits here will be overwritten — bump billing/version.py instead.
 */
(function () {
  window.SMIT_DOC = {
    version: '%s',
    build: '%s',
    updated: '%s',
    year: '%s',
    company: 'ООО «СмИТ»',
  };
  var v = window.SMIT_DOC;

  // Computed forms
  var forms = {
    version:        v.version,                                                // "1.6.0"
    vversion:       'v' + v.version,                                          // "v1.6.0"
    build:          v.build,                                                  // "170"
    vbuild:         'build ' + v.build,                                       // "build 170"
    full:           'v' + v.version + ' (build ' + v.build + ')',             // "v1.6.0 (build 170)"
    short:          v.version,                                                // "1.6.0" (alias of version)
    brand:          'СмИТ Биллинг ' + v.version,                              // "СмИТ Биллинг 1.6.0"
    'brand-short':  'СмИТ Биллинг ' + v.version.replace(/\\.0$/, ''),          // "СмИТ Биллинг 1.6"
    updated:        v.updated,
    year:           v.year,
    company:        v.company,
  };

  function apply() {
    document.querySelectorAll('[data-smit]').forEach(function (el) {
      var key = el.getAttribute('data-smit');
      if (forms.hasOwnProperty(key)) {
        el.textContent = forms[key];
      }
    });
    // Also allow meta tags to use data-smit-content="full" style
    document.querySelectorAll('meta[data-smit-content]').forEach(function (el) {
      var key = el.getAttribute('data-smit-content');
      if (forms.hasOwnProperty(key)) {
        el.setAttribute('content', (el.getAttribute('content') || '').replace(/\\{SMIT\\}/g, forms[key]));
      }
    });
    // <title> template support: if contains "{SMIT:full}" etc, replace
    if (document.title && /\\{SMIT:[a-z-]+\\}/.test(document.title)) {
      document.title = document.title.replace(/\\{SMIT:([a-z-]+)\\}/g, function (_, k) {
        return forms[k] || '';
      });
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', apply);
  } else {
    apply();
  }
})();
""" % (version, build, updated, year)

open('docs/js/version.js', 'w', encoding='utf-8', newline='\n').write(new_js)
print('  version.js → version=%s build=%s updated=%s year=%s' % (version, build, updated, year))
PYEOF
)

echo "=== 0. Sync version.js fallback values into HTML ==="
(cd "$HERE" && $PY - <<'PYEOF'
"""Подменяет fallback-значения в HTML на актуальные из js/version.js.

Источник истины — js/version.js. После запуска все вхождения <span data-smit="full">…</span>,
<span data-smit="build">…</span>, <span data-smit="updated">…</span> и заголовков с
"v1.6.0 (build NNN)" / "build NNN" в title/meta синхронизируются с переменными.
"""
import re, glob, os
js = open('js/version.js', 'r', encoding='utf-8').read()
def get(name):
    m = re.search(r"%s:\s*'([^']+)'" % name, js)
    return m.group(1) if m else None
v = {
    'version': get('version'),
    'build':   get('build'),
    'updated': get('updated'),
    'year':    get('year'),
    'company': get('company'),
}
if not all(v.values()):
    print('  WARN: cannot parse js/version.js — skip')
    raise SystemExit(0)
full = 'v%s (build %s)' % (v['version'], v['build'])
brand = 'СмИТ Биллинг %s' % v['version']
patterns = [
    # data-smit text fallback: capture the value tag and replace inner text
    (r'(<span data-smit="full"[^>]*>)v[\d.]+\s*\(build\s+\d+\)(</span>)',     r'\g<1>%s\g<2>' % full),
    (r'(<span data-smit="vversion"[^>]*>)v[\d.]+(</span>)',                    r'\g<1>v%s\g<2>' % v['version']),
    (r'(<span data-smit="version"[^>]*>)[\d.]+(</span>)',                      r'\g<1>%s\g<2>' % v['version']),
    (r'(<span data-smit="build"[^>]*>)\d+(</span>)',                           r'\g<1>%s\g<2>' % v['build']),
    (r'(<span data-smit="vbuild"[^>]*>)build\s+\d+(</span>)',                  r'\g<1>build %s\g<2>' % v['build']),
    (r'(<span data-smit="updated"[^>]*>)\d{2}\.\d{2}\.\d{4}(</span>)',         r'\g<1>%s\g<2>' % v['updated']),
    (r'(<span data-smit="year"[^>]*>)\d{4}(</span>)',                          r'\g<1>%s\g<2>' % v['year']),
    (r'(<span data-smit="brand"[^>]*>)[^<]*(</span>)',                         r'\g<1>%s\g<2>' % brand),
    # <title>API — СмИТ Биллинг v1.6.0 (build NNN)</title>
    (r'(СмИТ Биллинг\s+)v[\d.]+\s*\(build\s+\d+\)',                            r'\g<1>%s' % full),
    # SVG/text inside index.html: "v1.6.0 · build 214"
    (r'v[\d.]+\s*·\s*build\s+\d+',                                              'v%s · build %s' % (v['version'], v['build'])),
]
total = 0
for f in glob.glob('index.html') + glob.glob('pages/*.html'):
    src = open(f, 'r', encoding='utf-8').read()
    new = src
    for pat, repl in patterns:
        new = re.sub(pat, repl, new)
    if new != src:
        open(f, 'w', encoding='utf-8').write(new)
        total += 1
print('  updated %d files (version=%s build=%s updated=%s)' % (total, v['version'], v['build'], v['updated']))
PYEOF
)

echo "=== 1. Rebuild search index ==="
(cd "$HERE" && $PY - <<'PYEOF'
import re, json, os, glob, html
pages = []
for f in sorted(glob.glob('index.html') + glob.glob('pages/*.html')):
    with open(f, 'r', encoding='utf-8') as fp:
        txt = fp.read()
    for m in re.finditer(r'<(h[234])\s+id="([^"]+)"[^>]*>(.*?)</\1>', txt, re.DOTALL):
        tag, hid, inner = m.groups()
        title = html.unescape(re.sub(r'<[^>]+>', '', inner).strip())
        if not title: continue
        after = txt[m.end():m.end()+2000]
        plain = html.unescape(re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', ' ', after)).strip()[:240])
        pages.append({'t': title, 'id': hid, 'f': f.replace('\\','/'), 'c': plain})
with open('search-index.json', 'w', encoding='utf-8') as fp:
    json.dump(pages, fp, ensure_ascii=False, separators=(',',':'))
print(f"  wrote search-index.json — {len(pages)} entries, {os.path.getsize('search-index.json')} bytes")
PYEOF
)

echo "=== 2. Mirror to $MIRROR ==="
# Clear mirror (keep .git), then copy master content
find "$MIRROR" -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
cp -r "$HERE"/. "$MIRROR"/
if [ -d "$HERE/graphify" ]; then
  GRAPHIFY_FILES=$(find "$HERE/graphify" -type f | wc -l)
  echo "  synced (incl. graphify: $GRAPHIFY_FILES files)"
else
  echo "  synced"
fi

echo "=== 3. Commit + push in mirror repo ==="
cd "$MIRROR"
if [ -n "$(git status --porcelain)" ]; then
  git add -A
  git commit -m "$MSG"
  git push origin main
  echo "  pushed to github.com/ircitdev/docs.billing.smit34.ru"
else
  echo "  no changes to commit"
fi

echo "=== 4. Deploy to server ==="
cd "$HERE"
tar -czf /tmp/docs-deploy.tar.gz --exclude=sync-docs.sh --exclude=build_search_index.py .
scp /tmp/docs-deploy.tar.gz root@31.44.7.144:/tmp/
ssh root@31.44.7.144 "cd $SERVER_PATH && tar -xzf /tmp/docs-deploy.tar.gz && rm /tmp/docs-deploy.tar.gz && echo '  deploy OK'"
rm /tmp/docs-deploy.tar.gz

echo "=== DONE ==="
