#!/usr/bin/env bash
# sync-docs.sh — sync master (carbon_modern/docs/) to mirror (docs/),
# commit+push to docs.billing.smit34.ru, deploy to production server.
#
# Usage: from carbon_modern/docs/ dir, run:  ./sync-docs.sh "commit message"
#
# What it does:
#   1. Rebuild search index (search-index.json)
#   2. Mirror carbon_modern/docs/* -> ../../docs/  (excluding .git)
#   3. Commit + push in docs/ (separate docs.billing.smit34.ru repo)
#   4. Deploy same files to root@31.44.7.144:/var/www/docs.billing.smit34.ru/
#
# Master stays in carbon_modern/docs/ — always edit here.

set -euo pipefail

MSG="${1:-docs: sync from master}"
HERE="$(cd "$(dirname "$0")" && pwd)"
MIRROR="$(cd "$HERE/../../docs" && pwd)"
SERVER_PATH="/var/www/docs.billing.smit34.ru"

if command -v py >/dev/null 2>&1; then PY=py; else PY=python3; fi

echo "=== 0a. Auto-update version.js from billing/version.py + git log date ==="
(cd "$HERE/.." && PYTHONIOENCODING=utf-8 $PY - <<'PYEOF'
"""Авто-обновление docs/js/version.js — единого источника истины для подвала docs-сайта.

Источники:
  - VERSION / BUILD: billing/version.py (бампается при каждом деплое)
  - updated: дата последнего коммита, затронувшего carbon_modern/docs/ (в формате DD.MM.YYYY)
  - year: текущий год

Файл version.js перезаписывается полностью при каждом запуске sync-docs.sh.
После этого шаг 0 синхронизирует значения в HTML fallback-ы.
"""
import re, subprocess, sys
from datetime import datetime
sys.stdout.reconfigure(encoding='utf-8')

# 1. Read VERSION/BUILD from billing/version.py
src = open('billing/version.py', 'r', encoding='utf-8').read()
ver_m = re.search(r"VERSION\s*=\s*'([^']+)'", src)
bld_m = re.search(r"BUILD\s*=\s*'([^']+)'", src)
if not (ver_m and bld_m):
    print('  WARN: cannot parse billing/version.py — skip')
    raise SystemExit(0)
version, build = ver_m.group(1), bld_m.group(1)

# 2. Updated date: всегда сегодня (правки могут быть через scp, без коммита в основном репо).
#    Это тот день, когда оператор реально что-то поправил и запустил sync-docs.
updated = datetime.now().strftime('%d.%m.%Y')

year = str(datetime.now().year)

# 3. Rewrite docs/js/version.js
new_js = """/**
 * Single source of truth for the docs version/build/update date.
 * Auto-generated by sync-docs.sh from billing/version.py + last git commit date.
 * Manual edits here will be overwritten — bump billing/version.py instead.
 */
(function () {
  window.SMIT_DOC = {
    version: '%s',
    build: '%s',
    updated: '%s',
    year: '%s',
    company: 'ООО «СмИТ»',
  };
  var v = window.SMIT_DOC;

  // Computed forms
  var forms = {
    version:        v.version,                                                // "1.6.0"
    vversion:       'v' + v.version,                                          // "v1.6.0"
    build:          v.build,                                                  // "170"
    vbuild:         'build ' + v.build,                                       // "build 170"
    full:           'v' + v.version + ' (build ' + v.build + ')',             // "v1.6.0 (build 457)"
    short:          v.version,                                                // "1.6.0" (alias of version)
    brand:          'СмИТ Биллинг',                                            // без версии, см. brand-short
    'brand-short':  'СмИТ Биллинг',                                            // без версии: в шапке она устаревает быстрее страниц
    updated:        v.updated,
    year:           v.year,
    company:        v.company,
  };

  function apply() {
    document.querySelectorAll('[data-smit]').forEach(function (el) {
      var key = el.getAttribute('data-smit');
      if (forms.hasOwnProperty(key)) {
        el.textContent = forms[key];
      }
    });
    // Also allow meta tags to use data-smit-content="full" style
    document.querySelectorAll('meta[data-smit-content]').forEach(function (el) {
      var key = el.getAttribute('data-smit-content');
      if (forms.hasOwnProperty(key)) {
        el.setAttribute('content', (el.getAttribute('content') || '').replace(/\\{SMIT\\}/g, forms[key]));
      }
    });
    // <title> template support: if contains "{SMIT:full}" etc, replace
    if (document.title && /\\{SMIT:[a-z-]+\\}/.test(document.title)) {
      document.title = document.title.replace(/\\{SMIT:([a-z-]+)\\}/g, function (_, k) {
        return forms[k] || '';
      });
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', apply);
  } else {
    apply();
  }
})();
""" % (version, build, updated, year)

open('docs/js/version.js', 'w', encoding='utf-8', newline='\n').write(new_js)
print('  version.js → version=%s build=%s updated=%s year=%s' % (version, build, updated, year))
PYEOF
)

echo "=== 0. Sync version.js fallback values into HTML ==="
(cd "$HERE" && $PY - <<'PYEOF'
"""Подменяет fallback-значения в HTML на актуальные из js/version.js.

Источник истины — js/version.js. После запуска все вхождения <span data-smit="full">…</span>,
<span data-smit="build">…</span>, <span data-smit="updated">…</span> и заголовков с
"v1.6.0 (build NNN)" / "build NNN" в title/meta синхронизируются с переменными.
"""
import re, glob, os
js = open('js/version.js', 'r', encoding='utf-8').read()
def get(name):
    m = re.search(r"%s:\s*'([^']+)'" % name, js)
    return m.group(1) if m else None
v = {
    'version': get('version'),
    'build':   get('build'),
    'updated': get('updated'),
    'year':    get('year'),
    'company': get('company'),
}
if not all(v.values()):
    print('  WARN: cannot parse js/version.js — skip')
    raise SystemExit(0)
full = 'v%s (build %s)' % (v['version'], v['build'])
brand = 'СмИТ Биллинг %s' % v['version']
patterns = [
    # data-smit text fallback: capture the value tag and replace inner text
    (r'(<span data-smit="full"[^>]*>)v[\d.]+\s*\(build\s+\d+\)(</span>)',     r'\g<1>%s\g<2>' % full),
    (r'(<span data-smit="vversion"[^>]*>)v[\d.]+(</span>)',                    r'\g<1>v%s\g<2>' % v['version']),
    (r'(<span data-smit="version"[^>]*>)[\d.]+(</span>)',                      r'\g<1>%s\g<2>' % v['version']),
    (r'(<span data-smit="build"[^>]*>)\d+(</span>)',                           r'\g<1>%s\g<2>' % v['build']),
    (r'(<span data-smit="vbuild"[^>]*>)build\s+\d+(</span>)',                  r'\g<1>build %s\g<2>' % v['build']),
    (r'(<span data-smit="updated"[^>]*>)\d{2}\.\d{2}\.\d{4}(</span>)',         r'\g<1>%s\g<2>' % v['updated']),
    (r'(<span data-smit="year"[^>]*>)\d{4}(</span>)',                          r'\g<1>%s\g<2>' % v['year']),
    (r'(<span data-smit="brand"[^>]*>)[^<]*(</span>)',                         r'\g<1>%s\g<2>' % brand),
    # <title>API — СмИТ Биллинг v1.6.0 (build NNN)</title>
    (r'(СмИТ Биллинг\s+)v[\d.]+\s*\(build\s+\d+\)',                            r'\g<1>%s' % full),
    # SVG/text inside index.html: "v1.6.0 · build 214"
    (r'v[\d.]+\s*·\s*build\s+\d+',                                              'v%s · build %s' % (v['version'], v['build'])),
    # <title>...СмИТ Биллинг v1.6.0</title>, <meta og:title>, плейн-текст без build (build 861 fix)
    (r'(СмИТ Биллинг\s+)v[\d]+\.[\d]+\.[\d]+(?!\d|\s*\(build)',                r'\g<1>v%s' % v['version']),
    # Плейн «СмИТ Биллинг 1.6.0» без v (исключая историч. заголовки в changelog,
    # которые мы обходим — этот скрипт работает по всем .html, но «1.6.0» без v
    # в живых страницах встречается только как версия)
    (r'(СмИТ Биллинг\s+)[\d]+\.[\d]+\.[\d]+(?!\d)',                            r'\g<1>%s' % v['version']),
    # build 863: короткий формат «СмИТ Биллинг 1.6» без .0 (sidebar, title,
    # og-теги главной страницы) — приводим к v.version.replace('.0','') чтобы
    # получить «2.0» (или короче, как brand-short)
    (r'(СмИТ Биллинг\s+)[\d]+\.[\d]+(?![\d.])',                                r'\g<1>%s' % v['version'].rsplit('.', 1)[0]),
]
total = 0
for f in glob.glob('index.html') + glob.glob('pages/*.html'):
    src = open(f, 'r', encoding='utf-8').read()
    new = src
    for pat, repl in patterns:
        new = re.sub(pat, repl, new)
    if new != src:
        open(f, 'w', encoding='utf-8').write(new)
        total += 1
print('  updated %d files (version=%s build=%s updated=%s)' % (total, v['version'], v['build'], v['updated']))
PYEOF
)

echo "=== 0b. Sync sidebar from _nav.html ==="
# Меню физически скопировано в каждую страницу, и копии расходились молча:
# набралось девять вариантов, где-то не хватало целых групп, а у одной страницы
# группа была с заголовком, но без содержимого. Единственный источник —
# _nav.html; {PFX} — путь до pages/, {ROOT} — до корня сайта.
(cd "$HERE" && $PY - <<'NAVEOF'
import io, glob

nav = io.open('_nav.html', 'rb').read().decode('utf-8')
changed = []
for path in ['index.html'] + sorted(glob.glob('pages/*.html')):
    pfx, rt = ('pages/', '') if path == 'index.html' else ('', '../')
    block = nav.replace('{PFX}', pfx).replace('{ROOT}', rt)
    txt = io.open(path, 'rb').read().decode('utf-8')
    a, b = txt.index('<nav'), txt.index('</nav>') + len('</nav>')
    if txt[a:b] == block:
        continue
    io.open(path, 'wb').write((txt[:a] + block + txt[b:]).encode('utf-8'))
    changed.append(path)
print('  меню: %d пунктов, обновлено страниц: %d%s'
      % (nav.count('<li'), len(changed),
         (' (' + ', '.join(changed) + ')') if changed else ''))
NAVEOF
)

echo "=== 0c. Check links ==="
# Публиковать документацию с ссылками в никуда нельзя. Проверяем внутренние
# (#anchor), межстраничные (page.html#anchor) и каждую ссылку меню.
# Прежний шаблон [a-z_]+\.html не видел имён с дефисом, поэтому ссылки на
# nas-equipment.html и settings-services.html не проверялись вовсе.
# Обойти — SKIP_LINK_CHECK=1.
(cd "$HERE" && $PY - <<'LINKEOF'
import io, re, glob, os, sys

ids, bad = {}, {}
files = sorted(glob.glob('pages/*.html') + glob.glob('index.html'))
for f in files:
    ids[os.path.basename(f)] = set(
        re.findall(r'\sid="([^"]+)"', io.open(f, encoding='utf-8').read()))

LINK = re.compile(r'href="(?:pages/)?([A-Za-z0-9_-]+\.html)#([^"]+)"')
for f in files:
    name = os.path.basename(f)
    text = io.open(f, encoding='utf-8').read()
    for a in set(re.findall(r'href="#([^"]+)"', text)):
        if a not in ids[name]:
            bad.setdefault(name, set()).add('#' + a)
    for page, a in set(LINK.findall(text)):
        if page not in ids:
            bad.setdefault(name, set()).add(page + ' (нет страницы)')
        elif a not in ids[page]:
            bad.setdefault(name, set()).add(page + '#' + a)

# Меню проверяем отдельно: оно одно на весь сайт, и одна битая ссылка в нём
# повторилась бы на каждой странице.
nav = io.open('_nav.html', encoding='utf-8').read()
nav_links = re.findall(r'href="\{(PFX|ROOT)\}([^"]+)"', nav)
for pfx, href in nav_links:
    page, _, anchor = href.partition('#')
    path = ('pages/' + page) if pfx == 'PFX' else page
    if not os.path.exists(path):
        bad.setdefault('_nav.html', set()).add(href + ' (нет файла)')
        continue
    if anchor:
        have = set(re.findall(r'\sid="([^"]+)"',
                              io.open(path, encoding='utf-8').read()))
        if anchor not in have:
            bad.setdefault('_nav.html', set()).add(href)

total = sum(len(v) for v in bad.values())
if not total:
    print('  битых ссылок нет (в меню проверено %d)' % len(nav_links))
    sys.exit(0)
for name in sorted(bad):
    print('  %s (%d): %s' % (name, len(bad[name]), ', '.join(sorted(bad[name])[:8])))
if os.environ.get('SKIP_LINK_CHECK') == '1':
    print('  !! %d битых ссылок — пропущено (SKIP_LINK_CHECK=1)' % total)
    sys.exit(0)
print('  !! %d битых ссылок. Почините или запустите с SKIP_LINK_CHECK=1' % total)
sys.exit(1)
LINKEOF
)

echo "=== 1. Rebuild search index ==="
(cd "$HERE" && $PY - <<'PYEOF'
import re, json, os, glob, html


def page_name(txt, fname):
    """Человеческое имя страницы для выдачи поиска.

    В результатах «billing» ничего не говорит читателю, а <title> у каждой
    страницы уже написан по-русски — берём его, отрезая общий хвост с названием
    продукта и версией.
    """
    m = re.search(r'<title>(.*?)</title>', txt, re.S)
    if not m:
        return os.path.basename(fname).replace('.html', '')
    name = html.unescape(re.sub(r'<[^>]+>', '', m.group(1))).strip()
    name = re.split(r'\s+[—–-]\s+', name)[0].strip()
    return name or os.path.basename(fname).replace('.html', '')


pages = []
for f in sorted(glob.glob('index.html') + glob.glob('pages/*.html')):
    with open(f, 'r', encoding='utf-8') as fp:
        txt = fp.read()
    pname = page_name(txt, f)
    for m in re.finditer(r'<(h[234])\s+id="([^"]+)"[^>]*>(.*?)</\1>', txt, re.DOTALL):
        tag, hid, inner = m.groups()
        title = html.unescape(re.sub(r'<[^>]+>', '', inner).strip())
        if not title: continue
        after = txt[m.end():m.end()+2000]
        plain = html.unescape(re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', ' ', after)).strip()[:240])
        pages.append({'t': title, 'id': hid, 'f': f.replace('\\','/'),
                      'p': pname, 'c': plain})
with open('search-index.json', 'w', encoding='utf-8') as fp:
    json.dump(pages, fp, ensure_ascii=False, separators=(',',':'))
print(f"  wrote search-index.json — {len(pages)} entries, {os.path.getsize('search-index.json')} bytes")
PYEOF
)

echo "=== 2. Mirror to $MIRROR ==="
# Clear mirror (keep .git), then copy master content
find "$MIRROR" -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
cp -r "$HERE"/. "$MIRROR"/
if [ -d "$HERE/graphify" ]; then
  GRAPHIFY_FILES=$(find "$HERE/graphify" -type f | wc -l)
  echo "  synced (incl. graphify: $GRAPHIFY_FILES files)"
else
  echo "  synced"
fi

echo "=== 3. Commit + push in mirror repo ==="
cd "$MIRROR"
if [ -n "$(git status --porcelain)" ]; then
  git add -A
  git commit -m "$MSG"
  git push origin main
  echo "  pushed to github.com/ircitdev/docs.billing.smit34.ru"
else
  echo "  no changes to commit"
fi

echo "=== 4. Deploy to server ==="
cd "$HERE"
# TMPDIR задаётся снаружи: в Git Bash под Windows каталога /tmp нет и шаг падал
LOCAL_TMP="${DOCS_TMP:-/tmp}"
mkdir -p "$LOCAL_TMP"
tar -czf "$LOCAL_TMP/docs-deploy.tar.gz" --exclude=sync-docs.sh --exclude=update-understand.sh --exclude=build_search_index.py .
scp -O "$LOCAL_TMP/docs-deploy.tar.gz" root@31.44.7.144:/tmp/
ssh root@31.44.7.144 "cd $SERVER_PATH && tar -xzf /tmp/docs-deploy.tar.gz && rm /tmp/docs-deploy.tar.gz && echo '  deploy OK'"
rm "$LOCAL_TMP/docs-deploy.tar.gz"

echo "=== DONE ==="
