#!/usr/bin/env python3
"""Локализация интерфейса вьюера archify на русский.

archify поддерживает только `en` и `zh-CN`, поэтому русский добавляется
постобработкой уже проверенного артефакта:

1. встроенный рантайм-каталог `<script id="archify-i18n-data">` заменяется
   на русский из `viewer-ru.json`;
2. статические подписи, вшитые в разметку и SVG на этапе сборки, заменяются
   по тому же словарю — только в тексте вне `<script>`, чтобы не задеть логику;
3. `<html lang="en">` → `lang="ru"`.

Запуск:  python src/localize_ru.py            (все схемы рядом со скриптом)
         python src/localize_ru.py file.html  (одна схема)
"""
import html as html_mod
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RU_PATH = os.path.join(HERE, 'viewer-ru.json')
EN_PATH = os.path.join(HERE, 'viewer-en.json')
CATALOG_RE = re.compile(
    r'(<script id="archify-i18n-data"[^>]*>)(.*?)(</script>)', re.S)
SCRIPT_RE = re.compile(r'<script\b.*?</script>', re.S)
ATTRS = ('title', 'aria-label', 'aria-description', 'placeholder', 'alt', 'content')
# подписи, которые рендерер склеивает с авторским текстом, поэтому целиком
# они ни с одним ключом каталога не совпадают
SUBSTRINGS = (
    ('Architecture component', 'Компонент архитектуры'),
    ('Sequence participant', 'Участник'),
    ('Data-flow node', 'Узел потока данных'),
    ('Lifecycle state', 'Состояние'),
    ('Workflow node', 'Узел процесса'),
)
# служебная дорожка lifecycle нумеруется рендерером: «03 / Outcomes»
LANE_OUTCOMES_RE = re.compile(r'(\d+\s*/\s*)Outcomes')


def load_ru():
    with io.open(RU_PATH, encoding='utf-8') as fh:
        return json.load(fh)


def load_en():
    with io.open(EN_PATH, encoding='utf-8') as fh:
        return json.load(fh)


def replace_catalog(html, ru):
    """Меняет значения рантайм-каталога на русские, ключи не трогает."""
    match = CATALOG_RE.search(html)
    if not match:
        return html, {}
    data = json.loads(match.group(2))
    messages = data.get('messages', {})
    pairs = {}
    for key, value in list(messages.items()):
        translated = ru.get(key)
        if translated and translated != value:
            pairs[value] = translated
            messages[key] = translated
    data['locale'] = 'ru'
    data['messages'] = messages
    payload = json.dumps(data, ensure_ascii=False).replace('</', '<\\/')
    return html[:match.start(2)] + payload + html[match.end(2):], pairs


def build_static_pairs(ru, catalog_pairs):
    """Английский → русский для подписей, вшитых в разметку на этапе сборки.

    Пары берутся из эталонного английского каталога, поэтому повторный запуск
    на уже переведённом файле даёт тот же результат.
    """
    pairs = dict(catalog_pairs)
    english = load_en()
    for key, value in english.items():
        translated = ru.get(key)
        if translated and translated != value:
            pairs.setdefault(value, translated)
    # ключи рендер-времени (легенда, описания) в рантайм-каталог не попадают
    render_time = {
        'Legend': ru.get('legend.title'),
        # подпись служебной дорожки lifecycle, которую рендерер ставит сам
        'Outcomes': 'Выходы',
        'An architecture diagram generated by Archify.': ru.get('diagram.description.architecture'),
        'A workflow diagram generated by Archify.': ru.get('diagram.description.workflow'),
        'A sequence diagram generated by Archify.': ru.get('diagram.description.sequence'),
        'A data-flow diagram generated by Archify.': ru.get('diagram.description.dataflow'),
        'A lifecycle diagram generated by Archify.': ru.get('diagram.description.lifecycle'),
    }
    pairs.update({k: v for k, v in render_time.items() if v})
    return pairs


def replace_markup(html, pairs):
    """Заменяет текстовые узлы и подписи атрибутов вне <script>."""
    chunks = []
    last = 0
    scripts = []
    for match in SCRIPT_RE.finditer(html):
        chunks.append(html[last:match.start()])
        scripts.append(match.group(0))
        last = match.end()
    chunks.append(html[last:])

    def swap(segment):
        def text_node(match):
            raw = match.group(1)
            value = html_mod.unescape(raw).strip()
            if value not in pairs:
                return match.group(0)
            lead = raw[:len(raw) - len(raw.lstrip())]
            tail = raw[len(raw.rstrip()):]
            return '>' + lead + html_mod.escape(pairs[value], quote=False) + tail + '<'

        segment = re.sub(r'>([^<>]+)<', text_node, segment)

        for attr in ATTRS:
            def attr_value(match, attr=attr):
                value = html_mod.unescape(match.group(1)).strip()
                if value in pairs:
                    return '%s="%s"' % (attr, pairs[value].replace('"', '&quot;'))
                return match.group(0)

            segment = re.sub(r'%s="([^"]+)"' % attr, attr_value, segment)

        for english, russian in SUBSTRINGS:
            segment = segment.replace(english, russian)
        segment = LANE_OUTCOMES_RE.sub(r'Выходы', segment)
        return segment

    out = []
    for index, chunk in enumerate(chunks):
        out.append(swap(chunk))
        if index < len(scripts):
            out.append(scripts[index])
    return ''.join(out)


def localize(path, ru):
    with io.open(path, encoding='utf-8') as fh:
        html = fh.read()
    html, catalog_pairs = replace_catalog(html, ru)
    html = replace_markup(html, build_static_pairs(ru, catalog_pairs))
    html = re.sub(r'(<html[^>]*\blang=")en(")', r'\1ru\2', html, count=1)
    with io.open(path, 'w', encoding='utf-8', newline='') as fh:
        fh.write(html)
    return len(catalog_pairs)


def main():
    ru = load_ru()
    targets = sys.argv[1:]
    if not targets:
        targets = [os.path.join(ROOT, name) for name in sorted(os.listdir(ROOT))
                   if name.endswith('.html') and name != 'index.html']
    for path in targets:
        count = localize(path, ru)
        print('%-46s переведено значений каталога: %d' % (os.path.basename(path), count))


if __name__ == '__main__':
    main()
